/////////////////////////////////////////////////////////////////////////////////////////////////////////
// This configuration file was generated by the OAT Configurator at https://config.openastrotech.com for
// firmware Official Versions (V1.11.5 and later).
// Save this as Configuration_local.hpp in the folder where you placed the firmware code.
// Unique ConfigKey: FW:O,HS:N,BD:E,RS:N9,RD:TU,RAP900:O90:S8:T128:,RMSA3000:V1200:,RTR:N,RT:1,DS:N9,DD:TU,DAP900:O90:S16:T128:,DMSA3000:V1200:,DT:1,DY:NO,LM:N,FC:Y,FS:BY,FD:TU,FAP100:O80:S1:H10:,FMSA600:V250:,WW:N,GP:N,AP:N


// Use the much higher performance stepper library. 
#define NEW_STEPPER_LIB 

// We live in the Northern Hemisphere
#define NORTHERN_HEMISPHERE 1

// We are using the ESP32 board
//#if defined(BOARD) && BOARD != BOARD_ESP32_ESP32DEV
 //  #error Selected PIO environment does not match this configuration
//#else
    #define BOARD BOARD_ESP32_ESP32DEV
//#endif

////////////////////////////////
// RA Stepper configuration 
// See supported stepper values. Change according to the steppers you are using
// Using the NEMA 17, 0.9°/step stepper for RA
#define RA_STEPPER_TYPE STEPPER_TYPE_ENABLE

// Using the TMC2209-UART driver for RA stepper motor
#define RA_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define some RA stepper motor settings
#define RA_MOTOR_CURRENT_RATING       900 // mA
#define RA_OPERATING_CURRENT_SETTING  100 // %
#define RA_SLEW_MICROSTEPPING         8
#define RA_TRACKING_MICROSTEPPING     128

// Is it going the wrong way?
#define RA_INVERT_DIR  0

// Define some RA stepper motor settings
#define RA_STEPPER_ACCELERATION 3000
#define RA_STEPPER_SPEED 1800

// Track immediately after boot
#define TRACK_ON_BOOT 1

#ifdef NEW_STEPPER_LIB 
#define RA_SLEWING_ACCELERATION_DEG 2.0 // deg/s/s 
#define RA_SLEWING_SPEED_DEG 2.0 // deg/s 
#endif 

// Define limits for RA... 
#define RA_LIMIT_LEFT     5.5f
#define RA_LIMIT_RIGHT    6.5f
#define RA_TRACKING_LIMIT 6.75f // can't quite get to 7h...

// Using the 16 tooth gear (recommended) for RA belt
#define RA_PULLEY_TEETH 16

////////////////////////////////
// DEC Stepper configuration 
// See supported stepper values. Change according to the steppers you are using
// Using the NEMA 17, 0.9°/step stepper for DEC
#define DEC_STEPPER_TYPE STEPPER_TYPE_ENABLE

// Using the TMC2209-UART driver for DEC stepper
#define DEC_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define some DEC stepper motor settings
#define DEC_MOTOR_CURRENT_RATING       900 // mA
#define DEC_OPERATING_CURRENT_SETTING  90 // %
#define DEC_SLEW_MICROSTEPPING         16
#define DEC_GUIDE_MICROSTEPPING        128

// Is it going the wrong way?
#define DEC_INVERT_DIR  0

#ifdef NEW_STEPPER_LIB 
#define DEC_SLEWING_ACCELERATION_DEG 2.0 // degs/s/s 
#define DEC_SLEWING_SPEED_DEG 2.0 // deg/s 
#endif 

// Define some DEC stepper motor settings
#define DEC_STEPPER_ACCELERATION 3000
#define DEC_STEPPER_SPEED 1200

// Define DEC limits 

#define DEC_LIMIT_UP 113 // degrees from Home 
#define DEC_LIMIT_DOWN 65 // degrees from Home 

// Using the 16 tooth gear (recommended) for DEC belt
#define DEC_PULLEY_TEETH 16

#define RA_UART_STEALTH_MODE 0 
#define DEC_UART_STEALTH_MODE 0 

#define FOCUS_STEPPER_TYPE    STEPPER_TYPE_ENABLE
#define FOCUS_DRIVER_TYPE     DRIVER_TYPE_TMC2209_UART
#define FOCUS_STEPPER_SPR 2048.0f

#define FOCUS_MOTOR_CURRENT_RATING         100     // Current rating of focus motor in mA
#define FOCUS_OPERATING_CURRENT_SETTING  80     // Operating setting as a percentage of focus motor rating
#define FOCUS_MICROSTEPPING 1 // steps 
#define FOCUS_STEPPER_SPEED              400     // Default speed when moving focus motor in steps/s
#define FOCUS_STEPPER_ACCELERATION   250
#define FOCUS_UART_STEALTH_MODE            1     // Run the focuser silently
#define FOCUSER_ALWAYS_ON                1
#define FOCUSER_MOTOR_HOLD_SETTING       10 // %

//////////////////////////////// 
// Auto Homing addons 
#define USE_HALL_SENSOR_RA_AUTOHOME 1 
#define RA_HOMING_SENSOR_PIN 34 
#define RA_HOMING_SENSOR_SEARCH_DEGREES 10 

////////////////////////////////
// Display configuration 
// Define the type of display we are using. Currently: No display
#define DISPLAY_TYPE DISPLAY_TYPE_NONE

//////////////////////////////// 
// InfoDisplay configuration  
// Define the type of info display we are using. Currently: No info display 
#define INFO_DISPLAY_TYPE INFO_DISPLAY_TYPE_NONE 
#define INFO_DISPLAY_I2C_ADDRESS 0x3C 
#define INFO_DISPLAY_I2C_SDA_PIN 20 
#define INFO_DISPLAY_I2C_SCL_PIN 21 

////////////////////////////////
// WiFi configuration 
// Are we using WiFi: No, disable WiFi
#define WIFI_ENABLED 0

////////////////////////////////
// GPS Addon configuration 
// Define whether we have the GPS addon or not. Currently: No GPS
#define USE_GPS 0

////////////////////////////////
// AutoPA Addon configuration 
// Define whether we have the AutoPA add on or not. Currently: No AutoPA
// No AutoPA settings

///////////////////////
// Debug settings
#define DEBUG_LEVEL (DEBUG_NONE)
